package com.findback.model;

import java.time.LocalDateTime;

public class Item {

    private int id;
    private String title;
    private String category;
    private String location;
    private String status;
    private LocalDateTime dateReported;

    // Constructor for creating a new item
    // ID and dateReported will be generated by the database
    public Item(String title, String category, String location, String status) {
        this.title = title;
        this.category = category;
        this.location = location;
        this.status = status;
    }

    // Constructor for an item retrieved from the database
    public Item(int id, String title, String category,
                String location, String status,
                LocalDateTime dateReported) {

        this.id = id;
        this.title = title;
        this.category = category;
        this.location = location;
        this.status = status;
        this.dateReported = dateReported;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getDateReported() {
        return dateReported;
    }

    public void setDateReported(LocalDateTime dateReported) {
        this.dateReported = dateReported;
    }

    @Override
    public String toString() {
        return "Item{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", category='" + category + '\'' +
                ", location='" + location + '\'' +
                ", status='" + status + '\'' +
                ", dateReported=" + dateReported +
                '}';
    }
}